spring:
  datasource:
    url: jdbc:mysql://localhost:3306/res_establishment_area_db
    username: res_establishment_area_user
    password: USER@area
  # Zipkin
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411
  
  # Server
server:
  port: ${ESTABLISHMENT_AREA_SERVER_PORT}

  # Eureka
eureka:
  client:
    enabled: ${ESTABLISHMENT_AREA_EUREKA_CLIENT_ENABLED}
  serviceUrl:
    defaultZone: http://${ESTABLISHMENT_AREA_EUREKA_HOST}:${ESTABLISHMENT_AREA_EUREKA_PORT}/eureka