management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    mongo:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    version: '@project.version@'
    description: '@project.description@'

res:
  inventory:
    description: '@project.description@'
    quantity:
      fields-to-escape: ''
    version: '@project.version@'
    product:
      fields-to-escape: ''
    category:
      fields-to-escape: ''

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: none
    open-in-view: 'false'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '!nv3nT0Ry'
    username: res_inventory_manager
    url: jdbc:mysql://localhost:3306/res_inventory_db
  sleuth:
    sampler:
      percentage: '1.0'
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  cloud:
    service-registry:
      auto-registration:
        enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
    discovery:
      enabled: 'true'
  zipkin:
    enabled: 'false'
    baseUrl: http://localhost:9411

springdoc:
  swagger-ui:
    enabled: 'true'

eureka:
  client:
    instance-info-replication-interval-seconds: '120'
    enabled: ${INVENTORY_EUREKA_CLIENT_ENABLED}
    serviceUrl:
      defaultZone: http://${INVENTORY_EUREKA_HOST}:${INVENTORY_EUREKA_PORT}/eureka
      registerWithEureka: 'true'
    initial-instance-info-replication-interval-seconds: '120'
  instance:
    prefer-ip-address: 'true'

server:
  port: ${INVENTORY_SERVER_PORT}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        SQL: INFO
