management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    mongo:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

res:
  settings:
    template:
      fields-to-escape: ''
      freemarker:
        version: '@project.properties.freemarker.version@'
      path: freemarker-master-template.ftl
    paymentmethod:
      fields-to-escape: ''
    charge:
      fields-to-escape: ''
    device:
      fields-to-escape: ''
    description: '@project.description@'
    discount:
      fields-to-escape: ''
    deliverypartner:
      fields-to-escape: ''
    version: '@project.version@'

info:
  app:
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    version: '@project.version@'
    description: '@project.description@'

springdoc:
  swagger-ui:
    enabled: 'true'

spring:
  data:
    mongodb:
      host: localhost
      port: '27017'
      database: settings
  sleuth:
    sampler:
      percentage: '1.0'
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  cloud:
    service-registry:
      auto-registration:
        enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
    discovery:
      enabled: 'true'
  zipkin:
    enabled: 'false'
    baseUrl: http://localhost:9411

eureka:
  client:
    instance-info-replication-interval-seconds: '120'
    enabled: ${SETTINGS_EUREKA_CLIENT_ENABLED}
    serviceUrl:
      defaultZone: http://${SETTINGS_EUREKA_HOST}:${SETTINGS_EUREKA_PORT}/eureka
      registerWithEureka: 'true'
    initial-instance-info-replication-interval-seconds: '120'
  instance:
    prefer-ip-address: 'true'

server:
  port: ${SETTINGS_SERVER_PORT}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        SQL: INFO
